### ISSUE TITLE
iCal feed support (missing start/end times)

### ISSUE THREAD

**Issue by jvdp** [brightin/today#1]
I'm told these were removed from the XML feed. The iCal feed seems to still have this info though.

**Comment by florish** [comment]
Possible option for parsing iCal data in Ruby: https://github.com/tijn/virginity

Another option could be to rewrite this into a hubot script. I'm not sure whether hubot supports cron-like jobs running once a day.

**Comment by tijn** [comment]
I'm afraid Virginity can only parse vCards. It's a related format but you will have to do some serious hacking to use it for parsing iCal files.

I tried quickly rewriting today to use this ical-gem I found on the interwebs; but now it is confused by timezones :crying_cat_face: . You might find it interesting anyhow: https://github.com/tijn/today/tree/ical

Hubot or not is a completely unrelated issue.

**Comment by florish** [comment]
@tijn yep, hubot is completely unrelated, you're right :)

**Comment by florish** [comment]
I'm closing this issue, as we replaced the XML feed with the Calendar API, which provides event times.
